name: marketing_leads_pilot
version: "1.0"
config-version: 2
profile: marketing_leads_pilot

model-paths: [models]
seed-paths: [seeds]

models:
  marketing_leads_pilot:
    staging:
      +materialized: table

    intermediate:
      +materialized: table

    business_ready:
      +materialized: table