-- DML for DIM_LEAD_SOURCE
INSERT INTO DIM_LEAD_SOURCE (SOURCE_NAME)
SELECT DISTINCT LEAD_SOURCE FROM MARKETING_LEADS_RAW;

-- DML for FACT_LEADS
INSERT INTO FACT_LEADS (
    LEAD_ID, LEAD_SOURCE_KEY, CREATED_DATE, IS_QUALIFIED
)
SELECT
    rl.LEAD_ID,
    ls.SOURCE_KEY AS LEAD_SOURCE_KEY,
    DATE(rl.CREATED_AT) AS CREATED_DATE,
    CASE WHEN rl.STATUS = 'Qualified' THEN TRUE ELSE FALSE END AS IS_QUALIFIED
FROM MARKETING_LEADS_RAW rl
JOIN DIM_LEAD_SOURCE ls ON rl.LEAD_SOURCE = ls.SOURCE_NAME;