INSERT INTO T_MARKETING_LEADS (
    LEAD_ID,
    LEAD_SOURCE,
    CREATED_DATE,
    IS_QUALIFIED
)
SELECT
    f.LEAD_ID,
    ls.SOURCE_NAME AS LEAD_SOURCE,
    f.CREATED_DATE,
    f.IS_QUALIFIED
FROM FACT_LEADS f
JOIN DIM_LEAD_SOURCE ls ON f.LEAD_SOURCE_KEY = ls.SOURCE_KEY;