-- raw
CREATE OR REPLACE TABLE MARKETING_LEADS_RAW (
    LEAD_ID VARCHAR,
    LEAD_SOURCE VARCHAR,
    STATUS VARCHAR,
    CREATED_AT TIMESTAMP
);

-- tfm1
CREATE OR REPLACE TABLE am_ps_demo.dbt_projects.DIM_LEAD_SOURCE (
    SOURCE_KEY NUMBER PRIMARY KEY AUTOINCREMENT,
    SOURCE_NAME VARCHAR
);

-- tfm2
CREATE OR REPLACE TABLE  am_ps_demo.dbt_projects.FACT_LEADS (
    LEAD_ID VARCHAR PRIMARY KEY,
    LEAD_SOURCE_KEY NUMBER,
    CREATED_DATE DATE,
    IS_QUALIFIED BOOLEAN
);

-- bus ready
CREATE OR REPLACE TABLE  am_ps_demo.dbt_projects.T_MARKETING_LEADS (
    LEAD_ID VARCHAR,
    LEAD_SOURCE VARCHAR,
    CREATED_DATE DATE,
    IS_QUALIFIED BOOLEAN
);
