-- Raw Data Layer DDL
CREATE OR REPLACE TABLE MARKETING_LEADS_RAW (
    LEAD_ID VARCHAR,
    LEAD_SOURCE VARCHAR,
    STATUS VARCHAR,
    CREATED_AT TIMESTAMP
);

-- Intermediate Dimensional Model Layer DDL
CREATE OR REPLACE TABLE DIM_LEAD_SOURCE (
    SOURCE_KEY NUMBER PRIMARY KEY AUTOINCREMENT,
    SOURCE_NAME VARCHAR
);

CREATE OR REPLACE TABLE FACT_LEADS (
    LEAD_ID VARCHAR PRIMARY KEY,
    LEAD_SOURCE_KEY NUMBER,
    CREATED_DATE DATE,
    IS_QUALIFIED BOOLEAN
);

-- Business-Ready Layer DDL (now a table)
CREATE OR REPLACE TABLE T_MARKETING_LEADS (
    LEAD_ID VARCHAR,
    LEAD_SOURCE VARCHAR,
    CREATED_DATE DATE,
    IS_QUALIFIED BOOLEAN
);